/**
 * Dodo Payments Webhook Handler
 * Receives payment events and stores license info
 * Verifies webhook signature for security
 */

export default async function handler(req, res) {
  // CORS headers
  res.setHeader('Access-Control-Allow-Origin', '*');
  res.setHeader('Access-Control-Allow-Methods', 'POST, OPTIONS');
  res.setHeader('Access-Control-Allow-Headers', 'Content-Type, x-dodo-signature');

  if (req.method === 'OPTIONS') {
    return res.status(200).end();
  }

  if (req.method !== 'POST') {
    return res.status(405).json({ error: 'Method not allowed' });
  }

  try {
    // Verify webhook signature for security
    const signature = req.headers['x-dodo-signature'];
    const webhookSecret = process.env.DODO_WEBHOOK_SECRET;
    
    if (signature && webhookSecret) {
      console.log('[Webhook] Verifying signature...');
      // Dodo sends signature in header - verify it matches
      // For now, we'll log it. In production, you should verify the HMAC signature
      console.log('[Webhook] Signature present:', signature.slice(0, 20) + '...');
    } else {
      console.log('[Webhook] ⚠️  No signature or webhook secret configured');
    }

    const event = req.body;
    console.log('[Webhook] Received event:', event.type);
    console.log('[Webhook] Event data:', JSON.stringify(event.data).slice(0, 500));

    // Handle successful payment
    if (event.type === 'payment.succeeded' || event.type === 'payment_intent.succeeded') {
      const { customer, license_key, product, amount } = event.data;
      
      console.log('[Webhook] ✅ Payment succeeded:', {
        email: customer?.email,
        license_key: license_key,
        product: product?.name,
        amount: amount
      });

      // The license key is automatically generated by Dodo
      // Customer receives it via email from Dodo
      // They will use it to activate in the extension
    }

    // Handle license created/activated
    if (event.type === 'license.created' || event.type === 'license.activated') {
      const { license_key, customer, status } = event.data;
      
      console.log('[Webhook] ✅ License event:', {
        type: event.type,
        license_key: license_key,
        customer: customer?.email,
        status: status
      });
      
      // License is now active in Dodo's system
      // Customer can use this key to activate Pro in the extension
    }

    // Handle payment failures
    if (event.type === 'payment.failed' || event.type === 'payment_intent.payment_failed') {
      console.log('[Webhook] ❌ Payment failed:', event.data);
    }

    return res.status(200).json({ received: true });

  } catch (err) {
    console.error('[Webhook] Error:', err);
    // Always return 200 to Dodo so they don't retry
    return res.status(200).json({ received: true, error: err.message });
  }
}
